// PlayTogether/PlayTogether.WebClient/ClientApp/components/NavMenu.tsx
import * as React from 'react';
import { Link, RouteComponentProps, NavLink } from 'react-router-dom';

interface NavMenuProps {
    userName: string;
    isLoggedIn: boolean;
}

export class NavMenu extends React.Component<NavMenuProps, {}> {
    public render() {
        const { userName, isLoggedIn } = this.props;

        return <div className='main-nav'>
            <div className='navbar navbar-inverse'>
                <div className='navbar-header'>
                    <button type='button' className='navbar-toggle' data-toggle='collapse' data-target='.navbar-collapse'>
                        <span className='sr-only'>Toggle navigation</span>
                        <span className='icon-bar'></span>
                        <span className='icon-bar'></span>
                        <span className='icon-bar'></span>
                    </button>
                    {isLoggedIn && <Link className='navbar-brand' to={'/'}>Hi, {userName}</Link>}
                </div>
                <div className='clearfix'></div>
                <div className='navbar-collapse collapse'>
                    <ul className='nav navbar-nav'>
                        {isLoggedIn &&
                            <li>
                                <NavLink exact to={'/'} activeClassName='active'>
                                    Home
                            </NavLink>
                            </li>
                        }
                        {!isLoggedIn &&
                            <li>
                                <NavLink to={'/login'} activeClassName='active'>
                                    Login
                            </NavLink>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </div>;
    }
}

// PlayTogether/PlayTogether.Web/ClientApp/src/app/components/nav-menu/nav-menu.component.ts
import { Component } from '@angular/core';
import { Observable } from 'rxjs';
import { Store, select } from '@ngrx/store';
import { AppState } from '../../store';
import { Logout } from '../../store/auth/actions';

@Component({
  selector: 'app-nav-menu',
  templateUrl: './nav-menu.component.html',
  styleUrls: ['./nav-menu.component.css']
})
export class NavMenuComponent {
  isExpanded = false;
  userName$: Observable<string>;
  isLoggedIn$: Observable<boolean>;

  constructor(private store: Store<AppState>) {
    this.userName$ = this.store.pipe(select(s => s.auth.userName));
    this.isLoggedIn$ = this.store.pipe(select(s => s.auth.isLoggedIn));
  }

  collapse() {
    this.isExpanded = false;
  }

  toggle() {
    this.isExpanded = !this.isExpanded;
  }

  logout() {
    this.store.dispatch(new Logout());
  }
}

<div class='main-nav'>
    <div class='navbar navbar-inverse'>
        <div class='navbar-header'>
          <button type='button' class='navbar-toggle' data-toggle='collapse' data-target='.navbar-collapse' [attr.aria-expanded]='isExpanded' (click)='toggle()'>
            <span class='sr-only'>Toggle navigation</span>
            <span class='icon-bar'></span>
            <span class='icon-bar'></span>
            <span class='icon-bar'></span>
          </button>
          <div *ngIf="isLoggedIn$ | async">
            <a class='navbar-brand'>Привет, {{ userName$ | async }}</a>
            <a class='navbar-brand' href="javascript: " (click)="logout()">Выйти</a>
          </div>
        </div>
        <div class='clearfix'></div>
        <div class='navbar-collapse collapse' [ngClass]='{ "in": isExpanded }'>
            <ul class='nav navbar-nav'>
                <li [routerLinkActive]='["link-active"]' [routerLinkActiveOptions]='{ exact: true }'>
                    <a [routerLink]='["/"]' (click)='collapse()'>
                        <span class='glyphicon glyphicon-home'></span> Home
                    </a>
                </li>
            </ul>
        </div>
    </div>
</div>
